use_frameworks!

platform :ios, '9.0'

target 'PraiseAnimateSwift_Example' do
  pod 'PraiseAnimateSwift', :path => '../'

  target 'PraiseAnimateSwift_Tests' do
    inherit! :search_paths

    
  end
end
